version: 1

jobs:
  build:
    docker:
      - image: golang:1.11
    working_directory: /go/src/github.com/tarekbadrshalaan/modelgen
    steps:
      - checkout
      - run:
          name: "Build"
          command: go build .