
GET http://localhost:8899/actors/2

###
GET http://localhost:8899/actors
###
POST http://localhost:8899/actors

{   
    "actor_id": 201,
    "first_name": "foo",
    "last_name": "bar",
    "last_update": "2013-05-26T14:47:57.62Z"
}
###
PUT http://localhost:8899/actors

{   
    "actor_id": 201,
    "first_name": "foofoo",
    "last_name": "barbar",
    "last_update": "2017-05-26T14:10:10.62Z"
}
###
DELETE   http://localhost:7070/actors/201
###
GET http://localhost:8899/actors/201
###